apiVersion: v1
kind: Service
metadata:
  name: quoridor
spec:
  ports:
  - name: https
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: quoridor
  sessionAffinity: None
  type: ClusterIP
